-- Kör i samma DB (CMNDB) och schema-kontext som appen använder.
-- Exempel:
--   CONNECT TO CMNDB;
--   SET CURRENT SCHEMA DB2INST1;

CREATE TABLE FLOWMON_ACK (
  INCIDENT_ID   VARCHAR(512) NOT NULL PRIMARY KEY,
  ACKED_BY      VARCHAR(128) NOT NULL,
  ACKED_AT      TIMESTAMP    NOT NULL,
  EXPIRES_AT    TIMESTAMP    NULL,
  COMMENT_TXT   VARCHAR(512) NULL
);

CREATE INDEX IDX_FLOWMON_ACK_EXPIRES ON FLOWMON_ACK(EXPIRES_AT);

COMMIT;
